#!/bin/bash

DATECURRENT="$(date '+%Y-%m-%d')"
GLOUPSPATH="$(pwd)"
APPPATH=$GLOUPSPATH/src/js
VIEWSPATH=$GLOUPSPATH/src/js/views
PARTIALSPATH=$GLOUPSPATH/src/partials
ROUTERFILE="$GLOUPSPATH/src/js/routers/router.js"
ROUTER="$(cat $ROUTERFILE)"
BUILDPATH=$GLOUPSPATH/.generator

TPL="$(cat $BUILDPATH/view.js)"
TPLROUTE="$(cat $BUILDPATH/route.js)"



if [ $1 == "install" ]; then
  echo "\n> Install bower dependencies"
  bower install --quiet
  echo "> Install npm dependencies"
  npm install --quiet
  echo Replace  Gulp Header
  rm -r node_modules/gulp-header/
  unzip gulp-header.zip -d node_modules/
  echo "> You can."
fi

if [ $1 == "view" ]; then

  LOWER="$(echo $2 | tr '[:upper:]' '[:lower:]')"
  CAPITALIZE="${2^}"
  # Create the main view
  sed -e "s/==view==/$LOWER$/g"  -e "s/==viewCapitalize==/$CAPITALIZE/g" <<< "$TPL" > "$VIEWSPATH/$LOWER.js"

  # Create a partial
  echo "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus, earum, laudantium, commodi harum illum dolore sed voluptatum possimus qui odit reprehenderit vero ducimus veritatis voluptatem quidem? Ab necessitatibus repellendus perferendis." > "$PARTIALSPATH/$LOWER.html"

  # sed -e "s/'home': 'home'/'home': 'home',\n\t\t\t'$LOWER': '$LOWER'/g" <<< "$ROUTER" > $ROUTERFILE
  # Create a route
  AST="//==route==//";
  sed -e "s/'home': 'home'/'home': 'home',\n\t\t'$2': '$2'/g" -e "s,$AST,$TPLROUTE,g" -e "s/==view==/$2/g"  -e "s/==viewCapitalize==/$CAPITALIZE/g" <<< "$ROUTER" > $ROUTERFILE
fi
